#!/usr/bin/env python3
"""Generate the Kotlin lucide icon catalogue this library draws from.

lucide has no Kotlin port, so the icons are fetched once from the lucide
repository at a pinned tag and emitted as the inner markup of a 24x24 stroke
icon. Fetching beats hand-transcribing path data: a mistyped coordinate produces
a subtly wrong icon that no test would catch.

Only icons a consuming app actually uses are generated - a full lucide port would
be some 1,600 entries, and whole-program output means every one of them would be
weighed by the bundler. To add an icon, put its lucide file name in ICONS below
and re-run.

Run:  python3 tools/generate_lucide.py
Out:  keel/src/jsMain/kotlin/io/github/bchmsl/keel/icons/LucideIcons.kt
"""

from __future__ import annotations

import os
import re
import sys
import urllib.request

# Pinned rather than `main`, so a re-run reproduces the same icons.
LUCIDE_VERSION = "1.34.0"
SOURCE = "https://raw.githubusercontent.com/lucide-icons/lucide/{v}/icons/{name}.svg"

# lucide file names. An entry may be a (file name, Kotlin name) pair where lucide
# has renamed an icon and the older word is the one people search the code for.
ICONS = [
    # ---------------------------------------------------------- structure ----
    "chevron-down", "chevron-up", "chevron-left", "chevron-right",
    "arrow-right", "grip-vertical", "menu", "ellipsis-vertical",
    "maximize", "minimize", "maximize-2", "minimize-2", "x", "plus", "check",
    "house", "layout-grid",
    # `filter` was renamed `funnel` upstream. The Kotlin name keeps the older
    # word, which is what a tag-filter row is called everywhere else.
    ("funnel", "Filter"),

    # ------------------------------------------------------------ editing ----
    "pencil", "trash-2", "tag", "bold", "italic", "underline", "code",
    "link", "download",

    # ------------------------------------------------------ time and media ----
    "timer", "clock", "play", "pause", "skip-forward", "rotate-ccw", "rotate-cw",
    "volume-2", "volume-x", "cast",

    # ------------------------------------------------------------- weather ----
    "sun", "moon", "cloud", "cloud-sun", "cloud-drizzle", "cloud-rain",
    "cloud-snow", "cloud-lightning", "thermometer", "map-pin",

    # ---------------------------------------------------- state and system ----
    "loader-circle", "settings", "monitor", "palette", "zap",
    "bell", "bell-off", "log-out", "mail", "lock",
]

OUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "keel", "src", "jsMain", "kotlin", "io", "github", "bchmsl", "keel", "icons",
    "LucideIcons.kt",
)


def pascal_case(name: str) -> str:
    """`cloud-sun` -> `CloudSun`, `maximize-2` -> `Maximize2`."""
    return "".join(part[:1].upper() + part[1:] for part in name.split("-"))


def fetch_body(name: str) -> str:
    """Return the inner markup of an icon, with the outer <svg> wrapper removed.

    The wrapper's attributes (viewBox, stroke, stroke-width, linecap, linejoin)
    are identical for every lucide icon, so they live once in the Kotlin renderer
    rather than once per icon here.
    """
    with urllib.request.urlopen(SOURCE.format(v=LUCIDE_VERSION, name=name)) as response:
        svg = response.read().decode("utf-8")

    inner = re.sub(r"^.*?<svg[^>]*>", "", svg, flags=re.DOTALL)
    inner = re.sub(r"</svg>\s*$", "", inner, flags=re.DOTALL)
    # Collapse the pretty-printing: one line, no gaps between elements.
    inner = re.sub(r"\s+", " ", inner).strip()
    inner = re.sub(r">\s+<", "><", inner)

    if not inner:
        raise ValueError(f"{name}: no markup found")
    if '"""' in inner or "$" in inner:
        # Would break the Kotlin raw string this is emitted into.
        raise ValueError(f"{name}: markup contains a character the emitter cannot quote")
    return inner


def main() -> None:
    wanted = {
        (entry, pascal_case(entry)) if isinstance(entry, str) else entry
        for entry in ICONS
    }

    icons = []
    for file_name, kotlin_name in sorted(wanted, key=lambda pair: pair[1]):
        try:
            icons.append((kotlin_name, fetch_body(file_name)))
        except Exception as error:  # noqa: BLE001 - report and stop, never emit a partial file
            sys.exit(f"failed on '{file_name}': {error}")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as out:
        out.write(
            f'''// Generated by tools/generate_lucide.py from lucide {LUCIDE_VERSION}. Do not edit.
package io.github.bchmsl.keel.icons

/**
 * The lucide icons this library ships, as the inner markup of a 24x24 stroke icon.
 *
 * The wrapper attributes every lucide icon shares - the viewBox, `fill="none"`,
 * `stroke="currentColor"` and the 2px round-capped stroke - are applied once by
 * [Icon] rather than repeated here. `stroke="currentColor"` is what makes an icon
 * take the colour of the text around it, so a button hover recolours its icon with
 * no icon-specific rule anywhere.
 *
 * Regenerate with `python3 tools/generate_lucide.py` rather than editing.
 */
public enum class LucideIcon(internal val body: String) {{
'''
        )
        for kotlin_name, body in icons:
            out.write(f'    {kotlin_name}("""{body}"""),\n')
        out.write("}\n")

    print(f"  {OUT_PATH}")
    print(f"  {len(icons)} icons from lucide {LUCIDE_VERSION}")


if __name__ == "__main__":
    main()
